import xarray as xr
from pathlib import Path
import numpy as np

def modify_jcm_terrain(
    reference_file: str,
    output_directory: str = "./data",
):

    reference_file = Path(reference_file)
    output_directory = Path(output_directory)
    output_file = (output_directory / f"terrain_idealize_amazon.nc").resolve()
    output_directory.mkdir(parents=True, exist_ok=True)
    
    print(f"Modifying reference jcm terrain file: {str(reference_file)}")
    print(f"Target output file: {str(output_file)}")
    
    ds = xr.open_dataset(reference_file)
    print("Loaded xarray metadata")
    print(ds)
    
    llon, llat = np.meshgrid(
        ds.coords["lon"].to_numpy() % 360,
        ds.coords["lat"].to_numpy(),
        indexing = "ij",
    )
   
    land_lat_range = [-10, 10]
    land_lon_range = [90, 150]
   
    top_height = 5e3
    width = (land_lon_range[1] - land_lon_range[0]) * 0.5 
 
    mask = np.where(
        (
           (np.abs(llat) >= land_lat_range[0])
         & (np.abs(llat) <= land_lat_range[1])
         & (np.abs(llon) >= land_lon_range[0])
         & (np.abs(llon) <= land_lon_range[1])
        ),
        1,
        0,
    ).astype(int)
    
    ds["lsm"].data[:] = mask
    
    # In aqua planet, the orography at the point is still realistic earth, even
    # though the much of the surface is now ocean. Therefore, we need to set
    # the height of ocean grid to 0-meter, such that JCM does not see an invi-
    # sible mountain. 
    ds["orog"].data[:] = np.where(
        mask == 0,
        0.0,
        top_height * np.exp( - ( (llon - land_lon_range[0])**2 / (2 * width**2) ) )
    )
    
    print(f"Writing result to: {str(output_file)}")
    ds.to_netcdf(output_file)
    ds.close()
    return output_file



if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--reference-file", type=str, help="The reference terrain file generated by jcm.", required=True)
    parser.add_argument("--planet-type", type=str, help="The type of planet to generate.", choices=["capped_earth", "aquaplanet", "toy_earth"])
    parser.add_argument("--output-directory", type=str, help="Directory to output the file.", default=".")
    
    args = parser.parse_args()
    print(args)
    
    modify_jcm_terrain(args.reference_file, args.planet_type, args.output_directory)




